// Type-only compatibility shim. The old fetch-based `serverApi` client has been
// removed (Server-Actions-only app — no /api/* routes). All `import type`
// usages of this module keep working via the re-export below. Do NOT add
// runtime code here.
export type {
  Settings,
  PaymentMethod,
  Feature,
  Faq,
  Testimonial,
  WalletData,
  Order,
  ActionResult,
  HotmailProductOption,
  BulkMailProductOption,
  BulkMailCatalogPage,
  BulkMailCatalogDetails,
  BulkMailSupplierOrder,
  BulkMailSupplierOrderList,
  BulkMailOrderExport,
  FxRateInfo,
  AdminOverview,
  AdminProduct,
  AdminUser,
  AdminUserDetails,
  AdminOrder,
  AdminSettings,
  AdminPaymentMethod,
  AdminCategory,
  AdminActivityEvent,
  SupportMessage,
  SupportConversation,
  SupportThread,
  NotificationItem,
  DepositRequest,
  AdminDepositRequest,
  PurchaseOrder,
  PurchaseResult,
  OwnedEmail,
  GmailCodeResponse,
  GraphCodeResponse,
  GraphMailMessage,
  HotmailCodeResponse,
  HotmailLookupResponse,
  OutlookCodeResponse,
  TotpKeyMeta,
  TotpLiveCode,
  TotpCreateInput,
  TotpCreateResult,
  TotpPreviewResult,
} from "./types"
